### PR TITLE
Updated translations, fixed date datatype, new logo

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you.

Is ot really needed to have a setbjectNotExists followed by an extendObject "anytime"? Then you can replace that completely by a extendObject with the full object definition. Would be the same but wpuld touch maaaaany objects on each run ...

Additionally: Please do not delete the admin/i18n files! They are linked to Weblate so these are the new "Master "files and words.js is "just generated out of them". So please execute "gulp adminWords2languages" to split up the workds into these files again.

**Comment by klein0r** [comment]
> Additionally: Please do not delete the admin/i18n files! They are linked to Weblate so these are the new "Master "files and words.js is "just generated out of them". So please execute "gulp adminWords2languages" to split up the workds into these files again.

Oh, sorry 😄 I thought that process works directly on the `words.js`

> Is it really needed to have a setbjectNotExists followed by an extendObject "anytime"?

I don't know. Actually the object has the wrong type for all installations. Whats the best way to update that type just once?

**Comment by Apollon77** [comment]
> Whats the best way to update that type just once?

There is non really ... so maybe best to introduce a state with "object versionnnumber" and on start check if it is the "current version" and if not then execute a full extentObject  and else assume it is correct?

**Comment by klein0r** [comment]
What do you think about the last commit?

**Comment by GermanBluefox** [comment]
Thank you!

**Pull request merged**
